"""Task Executor - Executes task plans generated by TaskPlanner.

The Executor takes a structured ExecutionPlan and runs it.

Responsibilities:
1. Track task execution state
2. Handle dependencies (don't run task until dependencies complete)
3. Collect task results
4. Handle task failures (retry, skip, or abort)
5. Compose final result from all tasks

Key design:
- Executor is independent of Planner (can test separately)
- Executor maintains state during execution (task results, status)
- Executor coordinates with Supervisor for agent-based tasks
- Executor supports parallel execution where possible
"""

import asyncio
import logging
import time
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

from app.agents import SupervisorAgent
from app.orchestration.task_planner import ExecutionPlan, Task, TaskType

logger = logging.getLogger(__name__)


class TaskStatus(str, Enum):
    """Status of a task during execution."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    SKIPPED = "skipped"


@dataclass
class TaskResult:
    """Result of executing a single task."""

    task_id: str
    status: TaskStatus
    data: Any = None
    error: Optional[str] = None
    execution_time_ms: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class ExecutionResult:
    """Result of executing a complete plan."""

    plan: ExecutionPlan
    task_results: Dict[str, TaskResult]  # task_id -> TaskResult
    final_answer: str
    total_time_ms: float
    success: bool
    error: Optional[str] = None

    @property
    def completed_tasks(self) -> List[str]:
        """Task IDs that completed successfully."""
        return [
            task_id
            for task_id, result in self.task_results.items()
            if result.status == TaskStatus.COMPLETED
        ]

    @property
    def failed_tasks(self) -> List[str]:
        """Task IDs that failed."""
        return [
            task_id
            for task_id, result in self.task_results.items()
            if result.status == TaskStatus.FAILED
        ]


class TaskExecutor:
    """Executes structured task plans.

    Coordinates with Supervisor to execute agent-based tasks.
    Manages task state, dependencies, and error handling.
    """

    def __init__(self, supervisor: Optional[SupervisorAgent] = None):
        """Initialize executor.

        Args:
            supervisor: SupervisorAgent instance for routing queries to agents
        """
        self.supervisor = supervisor
        self.task_results: Dict[str, TaskResult] = {}
        logger.info("TaskExecutor initialized")

    async def execute(self, plan: ExecutionPlan) -> ExecutionResult:
        """Execute a task plan.

        Args:
            plan: ExecutionPlan from TaskPlanner

        Returns:
            ExecutionResult with all task results and final answer
        """
        start_time = time.time()
        logger.info(f"TaskExecutor.execute: {len(plan.tasks)} tasks")

        try:
            if plan.is_empty:
                return ExecutionResult(
                    plan=plan,
                    task_results={},
                    final_answer="No tasks to execute.",
                    total_time_ms=0,
                    success=True,
                )

            # Reset state for this execution
            self.task_results = {}

            # Execute tasks (respecting dependencies)
            await self._execute_tasks(plan)

            # Compose final answer from results
            final_answer = self._compose_answer(plan)

            elapsed_ms = (time.time() - start_time) * 1000

            result = ExecutionResult(
                plan=plan,
                task_results=self.task_results,
                final_answer=final_answer,
                total_time_ms=elapsed_ms,
                success=len(self.task_results) > 0,
            )

            logger.info(
                f"ExecutionResult: {len(result.completed_tasks)} completed, "
                f"{len(result.failed_tasks)} failed, elapsed_ms={elapsed_ms:.0f}"
            )

            return result

        except Exception as e:
            logger.error(f"ExecutionResult failed: {e}", exc_info=True)
            elapsed_ms = (time.time() - start_time) * 1000
            return ExecutionResult(
                plan=plan,
                task_results=self.task_results,
                final_answer=f"Execution failed: {str(e)}",
                total_time_ms=elapsed_ms,
                success=False,
                error=str(e),
            )

    async def _execute_tasks(self, plan: ExecutionPlan) -> None:
        """Execute all tasks in the plan, respecting dependencies.

        Args:
            plan: ExecutionPlan with tasks and dependencies
        """
        # Track which tasks are ready to execute
        waiting_for = {task.id: set(task.depends_on) for task in plan.tasks}

        while waiting_for:
            # Find tasks ready to execute (no dependencies left)
            ready = [task_id for task_id, deps in waiting_for.items() if len(deps) == 0]

            if not ready:
                # Check if we're stuck (circular dependency or missing dependency)
                logger.error("No tasks ready to execute but tasks remaining")
                break

            # Execute ready tasks in parallel
            tasks = [
                self._execute_task(task, plan)
                for task in plan.tasks
                if task.id in ready
            ]

            await asyncio.gather(*tasks)

            # Remove executed tasks from waiting list
            for task_id in ready:
                del waiting_for[task_id]

            # Update dependencies: remove completed tasks
            for deps in waiting_for.values():
                deps -= set(ready)

    async def _execute_task(self, task: Task, plan: ExecutionPlan) -> None:
        """Execute a single task.

        Args:
            task: Task to execute
            plan: Full plan (for context)
        """
        start_time = time.time()
        logger.info(f"Executing task {task.id}: {task.description}")

        try:
            # Mark as running
            self.task_results[task.id] = TaskResult(
                task_id=task.id,
                status=TaskStatus.RUNNING,
            )

            # Execute based on task type
            if task.type == TaskType.RETRIEVE_PROJECT:
                data = await self._retrieve_project(task.params)
            elif task.type == TaskType.RETRIEVE_RISKS:
                data = await self._retrieve_risks(task.params)
            elif task.type == TaskType.RETRIEVE_FINANCIALS:
                data = await self._retrieve_financials(task.params)
            elif task.type == TaskType.RETRIEVE_SCHEDULE:
                data = await self._retrieve_schedule(task.params)
            elif task.type == TaskType.SEARCH_DOCUMENTS:
                data = await self._search_documents(task.params)
            elif task.type == TaskType.SUMMARIZE:
                data = await self._summarize(task.params)
            elif task.type == TaskType.GENERATE_RECOMMENDATIONS:
                data = await self._generate_recommendations(task.params)
            elif task.type == TaskType.GENERATE_EXECUTIVE_SUMMARY:
                data = await self._generate_executive_summary(task.params)
            elif task.type == TaskType.ANALYZE:
                data = await self._analyze(task.params)
            else:
                data = f"Unknown task type: {task.type}"

            # Mark as completed
            elapsed_ms = (time.time() - start_time) * 1000
            self.task_results[task.id] = TaskResult(
                task_id=task.id,
                status=TaskStatus.COMPLETED,
                data=data,
                execution_time_ms=elapsed_ms,
            )

            logger.info(f"Task {task.id} completed in {elapsed_ms:.0f}ms")

        except Exception as e:
            logger.error(f"Task {task.id} failed: {e}", exc_info=True)
            elapsed_ms = (time.time() - start_time) * 1000
            self.task_results[task.id] = TaskResult(
                task_id=task.id,
                status=TaskStatus.FAILED,
                error=str(e),
                execution_time_ms=elapsed_ms,
            )

    async def _retrieve_project(self, params: Dict) -> str:
        """Retrieve project details using Supervisor."""
        project_id = params.get("project_id")
        if not self.supervisor or not project_id:
            return "Project data not available"

        response = await self.supervisor.answer(
            query=f"What is the status and details of project {project_id}?",
            project_id=project_id,
        )
        return response.get("answer", "")

    async def _retrieve_risks(self, params: Dict) -> str:
        """Retrieve risks using Supervisor."""
        project_id = params.get("project_id")
        if not self.supervisor or not project_id:
            return "Risk data not available"

        response = await self.supervisor.answer(
            query=f"What are the risks and blockers for project {project_id}?",
            project_id=project_id,
        )
        return response.get("answer", "")

    async def _retrieve_financials(self, params: Dict) -> str:
        """Retrieve financial data using Supervisor."""
        project_id = params.get("project_id")
        if not self.supervisor or not project_id:
            return "Financial data not available"

        response = await self.supervisor.answer(
            query=f"What is the budget and financial status of project {project_id}?",
            project_id=project_id,
        )
        return response.get("answer", "")

    async def _retrieve_schedule(self, params: Dict) -> str:
        """Retrieve schedule using Supervisor."""
        project_id = params.get("project_id")
        if not self.supervisor or not project_id:
            return "Schedule data not available"

        response = await self.supervisor.answer(
            query=f"What is the schedule and critical path for project {project_id}?",
            project_id=project_id,
        )
        return response.get("answer", "")

    async def _search_documents(self, params: Dict) -> str:
        """Search documents using Supervisor."""
        query = params.get("query", "")
        project_id = params.get("project_id")
        if not self.supervisor:
            return "Document search not available"

        response = await self.supervisor.answer(
            query=query,
            project_id=project_id,
        )
        return response.get("answer", "")

    async def _summarize(self, params: Dict) -> str:
        """Summarize results from dependent tasks."""
        # Collect results from dependent tasks
        dependent_ids = params.get("depends_on", [])
        summaries = []

        for task_id in dependent_ids:
            result = self.task_results.get(task_id)
            if result and result.status == TaskStatus.COMPLETED:
                summaries.append(result.data)

        # Use Supervisor to summarize
        combined = "\n".join(summaries)
        if self.supervisor:
            response = await self.supervisor.answer(
                query=f"Summarize the following information:\n{combined}",
            )
            return response.get("answer", combined)

        return combined

    async def _generate_recommendations(self, params: Dict) -> str:
        """Generate recommendations based on analysis."""
        # This would typically use an analysis task result
        return "Recommendations will be generated based on analysis."

    async def _generate_executive_summary(self, params: Dict) -> str:
        """Generate executive summary."""
        # Collect all previous results
        all_data = [result.data for result in self.task_results.values()]
        combined = "\n".join(str(d) for d in all_data if d)

        if self.supervisor:
            response = await self.supervisor.answer(
                query=f"Generate an executive summary for the following:\n{combined}",
            )
            return response.get("answer", combined)

        return combined

    async def _analyze(self, params: Dict) -> str:
        """Perform analysis on task results."""
        query = params.get("query", "")
        request = params.get("request", query)

        if not self.supervisor:
            return f"Analysis of: {request}"

        response = await self.supervisor.answer(query=request)
        return response.get("answer", "")

    def _compose_answer(self, plan: ExecutionPlan) -> str:
        """Compose final answer from all task results.

        Args:
            plan: ExecutionPlan

        Returns:
            Final answer string
        """
        # If there's a final generation task, use that
        final_tasks = [
            t
            for t in plan.tasks
            if t.type
            in (
                TaskType.GENERATE_EXECUTIVE_SUMMARY,
                TaskType.GENERATE_RECOMMENDATIONS,
                TaskType.SUMMARIZE,
            )
        ]

        if final_tasks:
            final_task_id = final_tasks[-1].id
            result = self.task_results.get(final_task_id)
            if result and result.status == TaskStatus.COMPLETED:
                return str(result.data)

        # Fallback: combine all results
        parts = []
        for task in plan.tasks:
            result = self.task_results.get(task.id)
            if result and result.status == TaskStatus.COMPLETED:
                parts.append(f"**{task.description}:**\n{result.data}")

        return "\n\n".join(parts) if parts else "Plan executed but no results."
